### ISSUE TITLE
nursery

### ISSUE THREAD

**Issue by RemkoDuursma** [CourtneyCampany/HIA_size_index#1]
OK looks good, but now I actually realize we might need some sort of indicator of the nursery, but de-identified. The reason is that any future analysis needs to take the nursery variance into consideration, and now we can't do that.

Also, probably need to remove lat/long as that can be used to find the nursery anyway.

You could do:
`nursery <- LETTERS[as.numeric(as.factor(nursery))]`, so that the first level turns into A, second to B, etc.

**Comment by RemkoDuursma** [comment]
Also - I can do this if you don't have the time right now.

**Comment by CourtneyCampany** [comment]
I can do it...tomorrow my time.

**Comment by CourtneyCampany** [comment]
done

**Comment by RemkoDuursma** [comment]
I only just saw you fixed this - thanks! Can you close the issue next time (then I get an email).
